### ISSUE TITLE
New Download URL for Lucid

### ISSUE THREAD

**Issue by Stette** [autopkg/macvfx-recipes#12]
Our override failed due to outdated URL in the Lucid.download.recipe.

Seems Lucid went from hosting the installer themselves to now using Cloudfront.

Old URL in recipe:  https://www.lucidlink.com/download/latest/osx/stable/
New URL when checking just now: https://d3il9duqikhdqy.cloudfront.net/latest/osx/lucid-2.6.5463.pkg

**Comment by markkenny** [comment]
[Got a working version as yaml.](https://github.com/markkenny/autopkg/blob/master/Lucid/Lucid.download.recipe.yaml)
```
Input:
  NAME: Lucid
  SEARCH_URL: https://www.lucidlink.com/download
  SEARCH_PATTERN: lucid-[0-9\.]*.pkg
  DOWNLOAD_URL: https://d3il9duqikhdqy.cloudfront.net/latest/osx

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: "%SEARCH_PATTERN%"
      url: "%SEARCH_URL%"

  - Processor: URLDownloader
    Arguments:
      url: "%DOWNLOAD_URL%/%match%"
      filename: "%NAME%.pkg"
```
